# Use the recommended rule set except for the standard_naming rule
extends: recommended
rules:
  standard_naming:
    level: disabled
  permissible_values_format:
    level: disabled
  no_empty_title:
    level: error
