---
site_name: "microbial-experiment-schema"
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: light blue
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
  - mermaid2:
      version: 10.9.0
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://usnistgov.github.io/microbial-experiment-schema
repo_url: https://github.com/usnistgov/microbial-experiment-schema

markdown_extensions:
  - pymdownx.tilde

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
