---
name: Auto-deployment of microbial_experiment_schema Documentation
on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry.
        run: pipx install poetry

      - name: Install dependencies.
        run: poetry install -E docs

      - name: Build documentation.
        run: |
          make build-site
          touch site/.nojekyll
      
      - uses: actions/upload-artifact@v4
        with:
          name: built-site
          path: site
          include-hidden-files: true